#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

if [ $(uname -n) != euler ]; then
	msens "USB OPTICAL MOUSE " -0.55
	setxkbmap -option numpad:mac us
fi

./.fehbg &
udiskie &
xbindkeys &
xmodmap ~/.Xmodmap &
xset -b &

exec i3
