#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

if [ $(uname -n) = euler ]; then
	msens "USB OPTICAL MOUSE " -0.9
	msens 'Logitech G305' -0.95
	setxkbmap -option numpad:mac us
	xrandr --output DP-0 --primary --auto --mode 2560x1440 --rate 120
	xrandr --output DVI-I-1 --left-of DP-0 --mode 1920x1080 --rotate left
fi

./.fehbg &
udiskie &
xbindkeys -f "$XDG_CONFIG_HOME"/xbindkeys/config
xmodmap "$XDG_CONFIG_HOME"/X11/xmodmap &
xrdb -load "$XDG_CONFIG_HOME"/X11/xresources
xset -b &

while true; do alacritty --class scratch; done &
exec i3
